#!/bin/bash
export DIRNAME=$(dirname $(which $0))
#get opt + filename
OPT=""
while [[ $# -gt 1 ]]; do
    OPT+=" $1"
    shift 
done
FILE=$1

filepp ${OPT}  -lc '&' -lr '&&' -imacros ${DIRNAME}/mnh_macro_expand.fpp ${FILE} | filepp ${OPT} -imacros ${DIRNAME}/mnh_macro_array_loop.fpp -M${DIRNAME} -m MNH.pm -c 
