#!/bin/bash
export DIRNAME=$(dirname $(which $0))
#
# Find/set module directory of original 'filepp'
#
if [ -s $(which filepp) ] ; then
export FILEPP=$( dirname $(which filepp) | sed -e 's|/bin||' )
export FILEPPMOD=${FILEPP}/share/filepp/modules
export PERL5LIB=${FILEPPMOD}:${PERL5LIB}
else
    echo "ERROR:: filepp is not in your PATH "
    exit 100
fi
#get opt + filename
OPT_FILEPP=""
OPT_CPP=""
#option to bypass CCP #macro -> replace # by @ in macro definition
NO_CPP=""
while [[ $# -gt 1 ]]; do    
    OPT_CPP+=" $1"
    case $1 in
	-DMNH_EXPAND_NOCPP)
	    NO_CPP="-kc @"
	    ;;	
	-DMNH_EXPAND*)
	    OPT_FILEPP+=" $1"
	    ;;	
	-d*)
	    OPT_FILEPP+=" $1"		
	    ;;
    esac
    shift      
done
FILE=$1

#echo OPT_FILEPP=${OPT_FILEPP}
#echo OPT_CPP=${OPT_CPP}
#echo FILE=${FILE}

#set -x

MNH_filepp  ${NO_CPP} -w ${OPT_CPP} ${FILE} | \
MNH_filepp ${OPT_FILEPP} -M${DIRNAME} -imacros ${DIRNAME}/mnh_macro_expand.fpp     -c -lc '&' -lr '@#@' | \
MNH_filepp ${OPT_FILEPP} -M${DIRNAME} -imacros ${DIRNAME}/mnh_macro_array_loop.fpp -c 
